# -*- coding: utf-8 -*-
"""codealpha_chatbot_project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1taVlezgy19ho47sg7q4vYgE43wmN-w6v

Libraries imported for chatbot project of common faqs
"""

import pandas as pd
import nltk
import string
from nltk.tokenize import word_tokenize,sent_tokenize
from nltk.corpus import stopwords
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity
nltk.download('punkt_tab')
nltk.download('stopwords')
from nltk.stem import WordNetLemmatizer
nltk.download('wordnet')

"""Database for chatbot , common shopping app FAQs

"""

# 1. The Raw Python Dictionary Database
faq_database = {
    "Category 1: Order Tracking & Status": [
        {"id": 1, "question": "Where is my order right now?", "answer": "You can track your order in real-time by going to My Orders, selecting your active purchase, and clicking Track Package."},
        {"id": 2, "question": "How long will it take for my package to arrive?", "answer": "Standard delivery timelines vary based on your location and the seller's shipping speed. The dynamic estimated arrival window is displayed at checkout.", "alt_phrasings": [
            "how much time does shipping take",
            "how long does delivery take",
            "when will my parcel arrive",
            "shipping time",
            ]},
        {"id": 3, "question": "My order status says 'Delivered', but I haven't received it. What should I do?", "answer": "Sometimes carriers update delivery status early. Please check with your neighbors or building security. If it is still missing after 24 hours, contact customer support."},
        {"id": 4, "question": "Can I change the delivery address after placing an order?", "answer": "Delivery addresses can only be modified before the seller packs or ships the package. Go to My Orders > Change Delivery Address to check eligibility."}
    ],
    "Category 2: Cancellations & Modifications": [
        {"id": 5, "question": "How do I cancel my order?", "answer": "Navigate to My Orders, click Cancel My Order, select your cancellation reason, and submit. Orders cannot be canceled once they are packed or shipped."},
        {"id": 6, "question": "I accidentally ordered the wrong size/color. Can I change it before it ships?", "answer": "Once confirmed, individual item variants cannot be modified inside the order. Please cancel the current order immediately and place a new one."},
        {"id": 7, "question": "Can I add another item to an order I just placed?", "answer": "We cannot add items to an existing finalized order. Please place a separate standalone order for any additional items."}
    ],
    "Category 3: Returns & Refunds": [
        {"id": 8, "question": "What is your return policy and how many days do I have to return an item?", "answer": "Most items are eligible for a return within 14 days of delivery if they are unused, undamaged, and kept in original manufacturer packaging."},
        {"id": 9, "question": "How do I print a return shipping label?", "answer": "Go to My Orders > Return My Order, fill out the return form, and select 'Drop-off'. A prepaid return shipping label will be generated for you to print."},
        {"id": 10, "question": "How long does it take to get my money back after a refund is approved?", "answer": "Refunds to digital wallets take 30 minutes, bank account direct transfers take about 5 working days, and credit/debit card reversals take 10 working days."},
        {"id": 11, "question": "I received a damaged or incorrect item. How can I replace it?", "answer": "Open My Orders, tap Initiate a Return, select 'Item is damaged/defective' or 'Incorrect item', and upload clear photos to request a free return or replacement."}
    ],
    "Category 4: Payments & Promo Codes": [
        {"id": 12, "question": "What payment methods do you accept?", "answer": "We accept major Credit/Debit Cards, integrated Digital Mobile Wallets, Easy Monthly Installments (EMI), and Cash on Delivery (COD).", "alt_phrasings": [
            "how can I pay",
            "what cards do you take",
            "how do I pay for my order",
            "who can I pay with"
        ]},
        {"id": 13, "question": "Why is my credit card/debit card being declined at checkout?", "answer": "Declines are usually caused by an incorrect CVV/expiry date, insufficient account funds, or missing international/e-commerce activation on your card."},
        {"id": 14, "question": "How do I apply a discount coupon or promo code to my cart?", "answer": "Enter your voucher code in the 'Apply Voucher' field on the checkout page and click apply before placing your order."},
        {"id": 15, "question": "Do you offer Cash on Delivery (COD)?", "answer": "Yes, Cash on Delivery is available for eligible delivery zones and order amounts. Choose COD during the payment phase at checkout."}
    ],
    "Category 5: Account & Security": [
        {"id": 16, "question": "I forgot my password. How do I reset it?", "answer": "Click Forgot Password on the login screen, enter your registered email or phone number, and follow the link or OTP instructions sent to you."},
        {"id": 17, "question": "How do I update my phone number or saved shipping address?", "answer": "Go to My Account > My Profile or Saved Addresses to add, edit, or clear your contact and delivery location information."},
        {"id": 18, "question": "How do I delete my account permanently?", "answer": "Navigate to Account Settings > Privacy & Security and request account deletion. This will permanently remove your data and purchase history."}
    ],
    "Category 6: Product Availability & Pricing": [
        {"id": 19, "question": "An item I want is out of stock. Can I get notified when it's back?", "answer": "If an item is out of stock, click the 'Wishlist' or 'Notify Me' icon on the product listing page to receive an alert when the seller restocks."},
        {"id": 20, "question": "Do you offer international shipping, or do you only deliver locally?", "answer": "We offer fast local shipping nationwide. Select global items can be bought through our dedicated international shipping filter options."}
    ]
}


rows = [
    {"ID": item["id"], "Category": cat, "Question": item["question"], "Answer": item["answer"]}
    for cat, items in faq_database.items() for item in items
]
pd.DataFrame(rows).to_csv("shopping_faqs.csv", index=False, encoding="utf-8")
pd.read_csv("shopping_faqs.csv").head()

"""Data preprocessing using nltk"""

lemmatizer = WordNetLemmatizer()

stop_words = set(stopwords.words('english'))

for category, items in faq_database.items():
    for item in items:
        # keep raw text untouched — never overwritten
        item['question_raw'] = item['question']
        item['answer_raw'] = item['answer']

        # build new processed fields, don't touch the originals
        item['question_tokens'] = [
            w for w in nltk.word_tokenize(item['question_raw'].lower())
            if w not in stop_words
        ]
        item['answer_tokens'] = [
            w for w in nltk.word_tokenize(item['answer_raw'].lower())
            if w not in stop_words
        ]

        item['question_clean'] = [
            lemmatizer.lemmatize(w) for w in item['question_tokens']
            if w not in string.punctuation and w.isalpha()
        ]
        item['answer_clean'] = [
            lemmatizer.lemmatize(w) for w in item['answer_tokens']
            if w not in string.punctuation and w.isalpha()
        ]
  # NEW: fold alt phrasings into question_clean so the vectorizer
        # learns those extra words too
        alt_phrasings = item.get('alt_phrasings', [])
        for phrase in alt_phrasings:
            phrase_tokens = [
                w for w in nltk.word_tokenize(phrase.lower())
                if w not in stop_words
            ]
            phrase_clean = [
                lemmatizer.lemmatize(w) for w in phrase_tokens
                if w not in string.punctuation and w.isalpha()
            ]
            item['question_clean'].extend(phrase_clean)

rows = [
    {
        "ID": item["id"], "Category": cat,
        "Question": item["question_raw"], "Answer": item["answer_raw"],
        "Question_Tokens": item["question_tokens"], "Answer_Tokens": item["answer_tokens"]
    }
    for cat, items in faq_database.items() for item in items
]
df = pd.DataFrame(rows)
df.head()

"""tf-idf vectorization and cosine similarity"""

faq_items = [item for items in faq_database.values() for item in items]

# Use question_clean directly — analyzer=lambda x: x tells the vectorizer
# "don't tokenize this yourself, treat each list as already-tokenized"
vectorizer = TfidfVectorizer(analyzer=lambda tokens: tokens)
tfidf_matrix = vectorizer.fit_transform([item['question_clean'] for item in faq_items])

def get_best_answer(user_query, top_n=1):
    # preprocess the user query the exact same way the FAQ questions were processed
    query_tokens = [
        w for w in nltk.word_tokenize(user_query.lower())
        if w not in stop_words
    ]
    query_clean = [
        lemmatizer.lemmatize(w) for w in query_tokens
        if w not in string.punctuation and w.isalpha()
    ]

    # if nothing meaningful survives cleaning, don't even bother vectorizing
    if not query_clean:
        return [{"question": None, "answer": "Sorry, I didn't understand that. Could you rephrase your question?", "score": 0.0}]

    # transform (not fit_transform) — reuse the vocabulary learned from the FAQ set
    query_vector = vectorizer.transform([query_clean])

    # compare the query vector against every FAQ question vector
    similarities = cosine_similarity(query_vector, tfidf_matrix).flatten()

    # get indices of the top_n most similar questions, highest first
    top_indices = similarities.argsort()[::-1][:top_n]

    # Define a minimum similarity score to consider an answer valid
    min_score = 0.3 # You can adjust this threshold as needed

    # Get the score of the most similar question
    best_score = similarities[top_indices[0]]
# don't guass, print sorry to user
    if best_score < min_score:
        return [
            {
                "question": None,
                "answer": "Sorry, I don't have an answer for that. Could you try rephrasing, or ask about orders, payments, returns, or shipping?",
                "score": round(float(best_score), 3)
            }
        ]

    results = []
    for idx in top_indices:
        results.append({
            "question": faq_items[idx]['question_raw'],
            "answer": faq_items[idx]['answer_raw'],
            "score": round(float(similarities[idx]), 3)
        })
    return results
    # user interface for bot --------

print("💬 FAQ Chatbot (type 'quit' or 'exit' to stop)")
print("-" * 50)

while True:
    user_input = input("You: ")

    if user_input.lower() in ["quit", "exit", "bye"]:
        print("Bot: Goodbye! 👋")
        break

    results = get_best_answer(user_input, top_n=1)
    best = results[0]

    if best["score"] < 0.3:
        print("Bot: I'm not sure I understood that. Could you rephrase your question?")
    else:
        print(f"Bot: {best['answer']}")
        print(f"     (matched: \"{best['question']}\" | confidence: {best['score']:.2f})")

    print()  # blank line for readability

# quick test
# get_best_answer(" what are the payment  method  ?  ")